### ISSUE TITLE
Get footer content right

### ISSUE THREAD

**Issue by replaid** [ocaorg/2018-redesign#10]
Fr. Eric mentioned a phrasing issue with one of the items in the footer, but the entire list of Directories links was wrong. Put in Clergy, Parishes, etc. like existing site has in top nav under Directories.

File to edit: https://github.com/ocaorg/2018-redesign/blob/master/source/_includes/footer.html

**Comment by jafuhrman** [comment]
Done!

**Comment by replaid** [comment]
@jafuhrman Cool! Then you can close the issue at the bottom of the issue page. Thanks!

**Comment by jafuhrman** [comment]
OK - will do!
