### ISSUE TITLE
Add navigation

### ISSUE THREAD

**Issue by replaid** [ocaorg/2018-redesign#2]
- only big dropdown menu that works is "about"
- "about" doesn't work when you click on it
- all the buttons below "about" dont work

Fr. Eric, Dec 4 2017:

> I would note that many of the links are not active so hard to see what is going on in other drop down menus.

**Comment by jafuhrman** [comment]
got it

**Comment by replaid** [comment]
The About section is the only one with a dropdown in the design delivery ([see the About page there](https://projects.invisionapp.com/share/D2AU5LXCX#/screens/232710087) and hover over About.)

I have made About work when clicked.

**Comment by jafuhrman** [comment]
Looks good!! :)

**Comment by replaid** [comment]
Separated adding the dropdowns into issue #11.

Separated creating pages within the About section into issue #12.
