### ISSUE TITLE
Port utility classes from existing design

### ISSUE THREAD

**Issue by replaid** [ocaorg/2018-redesign#24]
We need to implement as many as possible of the classes from the existing design's ["kitchen sink" page](https://oca.org/sf/2012-08-30/kitchen-sink.php).

**Comment by ashtonlance** [comment]
@replaid Can you share access to the source?

**Comment by replaid** [comment]
@ashtonlance What I linked to is all I have. The version used in that kitchen sink link is not minified: https://oca.org/sf/2012-08-30/css/screen.css

**Comment by replaid** [comment]
This is done thanks to @ashtonlance. A `.legacy` class must go outside any markup that is to see styling for the old tags.

**Comment by replaid** [comment]
Can see these working here: https://ocaorg.github.io/2018-redesign/kitchen-sink.html
