### ISSUE TITLE
Copy changes from Fr Eric

### ISSUE THREAD

**Issue by replaid** [ocaorg/2018-redesign#6]
Fr. Eric on Dec 4 2017:

- [x] 3. It is Primatial election. Should we even have such a link on the drop down? (He has decided we should not.)
- [x] 4. Central Administration not admission
- [x] 5. Boards, Offices and Commissions (should have a comma and in plural)
- [x] 8. Under Works is there a better way to phrase Metropolitan's Teachings?

**Comment by jafuhrman** [comment]
I can't do it - see attached
![screenshot](https://user-images.githubusercontent.com/34108385/33784546-4cfb2566-dc2f-11e7-84b7-47d3b1d0950b.jpg)

**Comment by jafuhrman** [comment]
help! :)

**Comment by replaid** [comment]
Huh, apparently I sent you a link to a specific commit some time ago. You're looking at a specific commit. It's rather like looking at an old revision in a Google doc—it's there as a snapshot for historical purposes, not as the current state of anything and hence not editable. 

Also, the directory that has what goes on the comp site is `source/`, not `docs/`.

Couple ways to get out of that:

1. See that **Tree: 03557…** menu in the upper left? Click that and a selection window will come up. Under its **Branches** tab you'll see `gh-pages` and `master`. Choose `master` (since that is where we're doing all of our work).
2. If you just click **2018-redesign** at the very top of the page, you'll be dropped into the `master` (main) branch at the top level directory and all weirdness will be gone.

**Comment by jafuhrman** [comment]
I went to "Source" with no luck finding "admission" so I did a search and
found it on both "Source" and "docs" but I got that message with both.

**Comment by replaid** [comment]
Yeah, OK, I get the same thing. So you can follow the link from the search, then follow my first "way to get out of that" and be all set.

**Comment by jafuhrman** [comment]
Ah hah! Got it! Thank you! :D

**Comment by jafuhrman** [comment]
Dunno what to do about #3 and #8 -- if they give me the wording, I'll do it. But I got #4 & #5 done - at least I think I did (I hit "commit changes")

**Comment by replaid** [comment]
email to team: I propose to remove Primatial Election from home page "About the OCA" dropdown. OK?

**Comment by replaid** [comment]
email to team: Please provide a name for the new collection of MT's material. The designers used "Metropolitan's Teachings" as a placeholder, but everyone seems to agree that's weird.

**Comment by jafuhrman** [comment]
fine by me

**Comment by replaid** [comment]
@jafuhrman all clear to remove Primatial from home page menu per Fr Eric

**Comment by jafuhrman** [comment]
Done. All that's left is #8

**Comment by jafuhrman** [comment]
#8 is done -- unless "From the Metropolitan" is suddenly decided to not work
