### ISSUE TITLE
Add links for main features from home page

### ISSUE THREAD

**Issue by replaid** [ocaorg/2018-redesign#8]
Fr. Eric on Dec 4 2017: 

> 2. Where is the link on the landing page for scripture readings, saints, music and texts? They are popular so what can we do about that?

**Comment by ashtonlance** [comment]
Where is this supposed to live? In the navigation or?

**Comment by ashtonlance** [comment]
![orthodox_church_in_america](https://user-images.githubusercontent.com/13652692/39780512-7e80abf2-52da-11e8-82ab-bcec1df6f420.png)

Something like this?

**Comment by replaid** [comment]
@ashtonlance Correct, that banner is what is moving up to the top.

**Comment by ashtonlance** [comment]
Right-o!
